//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimatePlaylist.Common.Mvc.Attributes.Enums
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UltimatePlaylist.Common.Mvc.Attributes.Enums.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInfo
        {
            get
            {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        public static string Code
        {
            get
            {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string DateCreated
        {
            get
            {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string DateUpdated
        {
            get
            {
                return ResourceManager.GetString("DateUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Id.
        /// </summary>
        public static string ExternalId
        {
            get
            {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question
        {
            get
            {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Question Name.
        /// </summary>
        public static string QuestionName
        {
            get
            {
                return ResourceManager.GetString("QuestionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname
        {
            get
            {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
    }
}
